### ISSUE TITLE
Maptime Summit Page needs a spot on the nav!

### ISSUE THREAD

**Issue by bethschechter** [maptime/maptime.github.io#161]
and maybe we turn it a color? like something purply? 
http://maptime.io/maptime-summit-2015/

**Comment by svmatthews** [comment]
Looks like you could add it to this file nad give it it's own classname for styling it differently! https://github.com/maptime/maptime.github.io/blob/master/_includes/menu.html

**Comment by bethschechter** [comment]
great! thanks Sam!

--
Beth Schechter
Education + Outreach, Stamen Design <http://stamen.com/>
Founder, Maptime <http://maptime.io/>
+1 415-558-1610

**Comment by bethschechter** [comment]
...i still need help. see pics in slack. #fail.

--
Beth Schechter
Education + Outreach, Stamen Design <http://stamen.com/>
Founder, Maptime <http://maptime.io/>
+1 415-558-1610

**Comment by geografa** [comment]
@bethschechter oof. that nav is a pain. I didn't expect a larger width in text there. I think we can reduce the .tab font-size and maybe the width. But 'Maptime Summit' needs to be on one line. Since this is a one-off, should this be in a separate element like the sidebar and not the nav? //cc @svmatthews
